### ISSUE TITLE
Are these examples valid?

### ISSUE THREAD

**Issue by kevinsteger** [BitMEX/api-connectors#136] opened 2018-05-16 20:41 UTC
This seems pretty basic and yet does not work.  Is there a version dependency that I am missing here that is a requirement to run this?

$pip install bitmex

```
import bitmex
apiKey = '...'
apiSecret = '...'
client = bitmex.bitmex(api_key=apiKey, api_secret=apiSecret)
print client.Quote.Quote_get(symbol='XBTUSD').result()
```

File "/.../bitmex.py", line 4, in <module>
    client = bitmex.bitmex(api_key=apiKey, api_secret=apiSecret)
TypeError: 'module' object is not callable

**Comment by nguyenlong500** [comment] 2018-05-18 14:42
Hi,

this is exactly their example and it was working fine until recently. I actually got the results back about a day ago then it started to break.

**Comment by ryanfox** [comment] 2018-05-21 16:44
Looks like you're using python 2:

    print client.Quote.Quote_get(symbol='XBTUSD').result()

Try Python 3, 2 is not supported.

**Comment by nguyenlong500** [comment] 2018-05-21 17:11
I'm using python3 and I have the same error.

**Comment by ryanfox** [comment] 2018-05-21 18:03
Are you calling `bitmex()` or `bitmex.bitmex()`? Depending on how you import it, you may be calling the function or the module. You can't call the module, that's what `'module' object is not callable` means.

This should work:

    import bitmex
    client = bitmex.bitmex(...)

**Comment by bsdo64** [comment] 2018-05-23 04:11
Currently, /quote endpoint is not active with no announcememt. I asked reddit  [here](https://www.reddit.com/r/BitMEX/comments/8kroj5/bitmex_quote_api_doesnt_work/)

**Comment by ryanfox** [comment] 2018-07-27 20:38
`/quote` is returning valid results for me on both testnet and live. Closing this unless the issue is still reproducible.

**Closed by ryanfox** 2018-07-27 20:38 UTC

**Comment by TMAX0914** [comment] 2018-07-30 14:01
In my case, I made a file named 'bitmex.py' in my working directory. Then, I also got a same problem with kevinsteger.
Of course, it was recovered after changing the file name.

**Comment by Kinzowa** [comment] 2020-01-19 19:18
> `/quote` is returning valid results for me on both testnet and live. Closing this unless the issue is still reproducible.

What is the alternative option to get ask and bid?

**Comment by Z-VV** [comment] 2021-12-13 15:48
Change the name of your .py file if it's current name is bitmex.py
