### ISSUE TITLE
Keep getting this issue: 403

### ISSUE THREAD

**Issue by BitHitBin** [BitMEX/api-connectors#143] opened 2018-05-28 05:37 UTC
I'm trying to get a quote and post an order and I keep getting these messages:

Response specification matching http status_code 403 not found for operation Operation(Order_new). Either add a response specification for the status_code or use a `default` response.

Response specification matching http status_code 403 not found for operation Operation(Quote_get). Either add a response specification for the status_code or use a `default` response.

Also this one: KeyError: 'tickLog'

Everything works great on the testnet, but not live. Also the API keys have all permissions.

Am I missing something?

**Comment by macro655** [comment] 2018-05-29 01:26
You aren't the only one :) See [here](https://github.com/BitMEX/api-connectors/issues/141)

**Comment by ryanfox** [comment] 2018-05-29 17:25
Duplicate of #141. Closing.

**Closed by ryanfox** 2018-05-29 17:25 UTC
