### ISSUE TITLE
'Quote' Endpoint 403 Forbidden Error

### ISSUE THREAD

**Issue by macro655** [BitMEX/api-connectors#141] opened 2018-05-25 10:20 UTC
Hi,

I'm getting a 403 error on the quote endpoint even via the Interactive REST API Explorer, no matter what parameters I use. 

Is this endpoint temporarily down or is it being deprecated permanently?

Thanks!

**Comment by typerx** [comment] 2018-05-26 12:32
Hi got this same error. Any solution?

**Comment by BitHitBin** [comment] 2018-05-28 05:40
Same here! Been getting an error for the Quote_get and Order_new.

**Comment by typerx** [comment] 2018-05-28 15:02
as workaround, i am using OrderBook/L2

**Comment by macro655** [comment] 2018-05-29 01:42
Response from Bitmex support: "Currently, our /quote endpoint is disabled. We have temporarily disabled the endpoint to ensure smooth engine performance.  At this stage, we do not have an estimated time as to when this will be back up and running, but there will be an announcement when this has been resolved."

**Comment by undiabler** [comment] 2018-06-29 14:40
client.Order.Order_new isnt working for testnet (get same 403 error)
so there is no way to place orders by api for now?

**Comment by STRML** [comment] 2018-06-29 14:49
If you're receiving a 403 on new orders your key may be disabled or your IP banned.

**Comment by ryanfox** [comment] 2018-07-27 20:40
I receive valid responses for `/quote` from both testnet and live. Closing unless the issue is still reproducible.

**Closed by ryanfox** 2018-07-27 20:40 UTC

**Comment by GoldRat** [comment] 2018-08-14 14:45
I receive error 403 responses for /quote from both testnet and live. Even in REST API Explorer.

**Comment by chillz561** [comment] 2018-08-15 12:18
My code works perfect  on testnet but when i switch to live i get the same errors to

bravado.exception.HTTPForbidden: 403 Forbidden: Response specification matching http status_code 403 not found for operation Operation(Quote_get). Either add a response specification for the status_code or use a `default` response.

and also this error happens when switching to live nothing works
IndexError: list index out of range

**Comment by tanzeelrana** [comment] 2018-08-28 05:12
Running the app locally. I had a CORS issue so I turned on the CORS plugin. That error went away but now I get 403 TypeError: Failed to fetch. I am trying to fetch orders.

**Comment by architkshk** [comment] 2018-08-28 16:32
facnig same problem as @tanzeelrana

**Comment by sadgb** [comment] 2018-09-05 13:59
+1

**Comment by CaptJakk** [comment] 2018-10-21 22:02
+1

**Comment by geekkun** [comment] 2018-10-23 13:53
+1

**Comment by beeflowers287** [comment] 2018-12-04 19:15
> as workaround, i am using OrderBook/L2

The #BitMEX API is fragmented at best, verging on broken. You can barely get a public price quote (they turned off that endpoint sometime in 2018) so I wanted to share an all in one I've hacked together from their api over the past 6 months for CT and my sanity:

1/ Price
Work around to get the current price is using another endpoint. orderBook/L2 python:

```
import requests, json
response = requests.get("https://www.bitmex.com/api/v1/orderBook/L2?symbol=eth&depth=1 …").json()
ether_bid_price = response[1]['price']
```

2/ Everything else
Digging thru the open Issues of the bitmex github repo this is the best resource I found to help you place/ammend/cancel orders without downloading their sorry excuse sample market maker bot: https://github.com/mazmex7/BitMEX-API-python … 
Thank you @mazmex7

**Comment by xiaoxiaoleo** [comment] 2019-01-12 16:59
+1

`<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
</body>
</html>
`

**Comment by bitRomney** [comment] 2019-01-12 19:11
https://medium.com/@mbrando2_99725/pip-install-bitmex-calls-official-lib-code-89b08ceaabf9

**Comment by theclai** [comment] 2019-02-12 04:02
any solution of this error ? its 2019 and still got same error 

The remote server returned an error: (403) Forbidden.

**Comment by bitRomney** [comment] 2019-02-15 22:15
> any solution of this error ? its 2019 and still got same error
> 
> The remote server returned an error: (403) Forbidden.

https://github.com/BitMEX/api-connectors/issues/141#issuecomment-444222187

**Comment by theclai** [comment] 2019-02-18 12:47
> > any solution of this error ? its 2019 and still got same error
> > The remote server returned an error: (403) Forbidden.
> 
> [#141 (comment)](https://github.com/BitMEX/api-connectors/issues/141#issuecomment-444222187)

I got error when try to make an order like buy or sell for get Price Quote was not error

**Comment by wlk** [comment] 2019-03-07 07:51
Official API is broken, but quote endpoint is available if you setup BitMEX delta server, see: https://github.com/BitMEX/api-connectors/tree/master/official-ws/delta-server

**Comment by bitRomney** [comment] 2019-03-07 18:05
> Official API is broken, but quote endpoint is available if you setup BitMEX delta server, see: https://github.com/BitMEX/api-connectors/tree/master/official-ws/delta-server

Interesting. Didn't know about this. I'm a Python man myself and don't have a lot of experience with node.js servers. Would be nice if they had Python. It's amazing how broken BitMEX for developers' communication is.

**Comment by STRML** [comment] 2019-03-08 14:30
The reason this works is that only real-time data will be shown via the delta-server, as it accumulates in-memory tables from the websocket. Historical data is still not available through it, and historical quote data is what is disabled right now.

**Comment by GrilledChickenThighs** [comment] 2019-03-15 03:48
Well this is convenient...

**Comment by jsappme** [comment] 2019-04-16 22:10
this issue should be re-opened until it is fixed, no?

**Comment by tanmaykumar** [comment] 2019-04-18 04:46
This is a known issue - the endpoint has been disabled intentionally. I doubt that it will be enabled again until the API is less overloaded. Don’t see that happening soon, might probably take a few months.

**Comment by FM100X** [comment] 2020-05-04 20:23
Hi, any news here? I get this for many endpoints. How can I get historical data (1min Candlestick data)?

AttributeError: Resource Quote not found. Available resources: APIKey, Announcement, Chat, Execution, Funding, GlobalNotification, Instrument, Insurance, Leaderboard, Liquidation, Order, OrderBook, Position, Schema, Settlement, Stats, Trade, User, UserEvent

Thanks!
